ARG NODE_VERSION=20.11.1
ARG PNPM_VERSION=8.15.4
ARG TS_VERSION=5.3.3

FROM node:${NODE_VERSION}-slim

WORKDIR /usr/src/app

COPY . .

RUN npm install -g pnpm@${PNPM_VERSION} 
RUN npm install -g typescript@${TS_VERSION} 
RUN pnpm install --frozen-lockfile 

RUN mkdir -p /data
RUN chown -R node /data
USER node

ENV NODE_ENV production
ENV KEEP_DOWNLOADED_FILES false
ENV DOWNLOAD_SPEED_LIMIT -1
ENV UPLOAD_SPEED_LIMIT -1
ENV TORRENT_STORAGE_DIR /data
ENV TORRENT_SEED_TIME 60000
ENV TORRENT_TIMEOUT 5000

VOLUME /data

EXPOSE 8000

CMD pnpm start